### ISSUE TITLE
Godot removed? 

### ISSUE THREAD

**Issue by apsz3** [blueloveTH/pocketpy#11]
Why was the Godot plugin removed?

**Comment by apsz3** [comment]
Ah, I see it was moved to https://github.com/blueloveTH/godot-cpp/tree/master/pocketpy

Is the idea to reintegrate it into this repo? Or how will it be distributed?

**Comment by blueloveTH** [comment]
Currently, GDExtension is unstable. Their APIs often do break change.
Godot 4.0 stable is needed.

**Comment by blueloveTH** [comment]
I think we'd better think about distribution ideas after Godot 4.0 stable.

**Comment by apsz3** [comment]
makes sense.
