### ISSUE TITLE
std::min and std::max on Windows

### ISSUE THREAD

**Issue by shakfu** [blueloveTH/pocketpy#111]
Fyi, I was getting some compilation errors in `pocketpy.h` related to `std::min` and `std::max` on Windows. This is a well known issue (see [Stackoverflow](https://stackoverflow.com/questions/5004858/why-is-stdmin-failing-when-windows-h-is-included) on this): basically because windows has `min` and `max` macros defined.

The solution is quite simple to wrap `std::min` and `std::max` in brackets: `std::min` -> `(std::min)`  etc..

**Comment by blueloveTH** [comment]
Which version are you using now? This was already fixed in the main branch.

```
#ifdef min
#undef min
#endif

#ifdef max
#undef max
#endif
```

**Comment by shakfu** [comment]
I'm using 1.0.9 (the last release)

**Comment by shakfu** [comment]
Looks this was fixed in 1.10. Thanks!
