### ISSUE TITLE
VM as singleton

### ISSUE THREAD

**Issue by carlkl** [blueloveTH/pocketpy#127]
Can a pocketpy VM instance be created as singleton to be accessible across function boundaries?

**Comment by blueloveTH** [comment]
You can define a global variable `vm`.

```
static VM vm;
```

And this can be accessed by all your functions.

**Comment by carlkl** [comment]
I tried an approach similar to this one, as I want to access the VM from Fortran: https://community.intel.com/t5/Intel-Fortran-Compiler/Calling-C-cpp-objects-from-a-Fortran-subroutine/m-p/1110556

**Comment by blueloveTH** [comment]
Do not try to wrap a C++ object in another language. C++ is bad for communication, use C-APIs instead.

**Comment by carlkl** [comment]
Yes, ths is my alternative approach: static VM (C-Api) and use it from only one scope.
