### ISSUE TITLE
C-API and bind()

### ISSUE THREAD

**Issue by carlkl** [blueloveTH/pocketpy#128]
Is there a way to bind native functions with the C-API?

**Comment by blueloveTH** [comment]
```c
#include "pocketpy_c.h"
#include <stdio.h>
#include <stdlib.h>

static int hello(pkpy_vm* vm){
    printf("Hello world!\n");
    return 0;
}

int main(){
    pkpy_push_function(vm, "hello()", hello);
    pkpy_setglobal(vm, pkpy_name("hello"));
    pkpy_exec(vm, "hello()");
    return 0;
}
```

**Comment by blueloveTH** [comment]
#include "pocketpy_c.h"
#include <stdio.h>
#include <stdlib.h>

static int add(pkpy_vm* vm){
    int a, b;
    pkpy_to_int(vm, -2, &a);
    pkpy_to_int(vm, -1, &b);
    pkpy_push_int(vm, a+b);
    return 1;   // there is only 1 return value
}

int main(){
    pkpy_push_function(vm, "add(a, b)", add);
    pkpy_push_null(vm);
    pkpy_push_int(vm, 1);
    pkpy_push_int(vm, 2);
    pkpy_vectorcall(vm, 2);
    int x;
    pkpy_to_int(vm, -1, &x);
    pkpy_pop_top(vm);
    printf("%d\n", x);
    return 0;
}

**Comment by blueloveTH** [comment]
You may check each function's return value to determine there is no error.

**Comment by carlkl** [comment]
Very good help, as usual. Thank you very much!

**Comment by carlkl** [comment]
Sorry for the noise again, but there is a point I cannot find the correct solution:

If have a python script like that:

```python
A(1,2.5,5,'x')
B(3,'y')
C(2.0,3.0,'z')
```

all these functions are implemented in C and have a fixed function signature and can be called via `pkpy_vectorcall`. The order and number of functions to be called is defined in the script. Hence I want to bind these C functions to the `vm`. I may be missing the obvious, but I have no idea how to do it correctly in the stack based C-API.


BTW: in your examples in this issues the following line is missing in main():
```C
pkpy_vm* vm = pkpy_new_vm(true);
```

**Comment by blueloveTH** [comment]
I don't get it.

**Comment by carlkl** [comment]
I want something like

```C
    pkpy_push_function(vm, "A()", A);
    pkpy_setglobal(vm, pkpy_name("A"));
    pkpy_push_function(vm, "B()", B);
    pkpy_setglobal(vm, pkpy_name("B"));
    pkpy_push_function(vm, "C()", C);
    pkpy_setglobal(vm, pkpy_name("C"));
    pkpy_exec(vm, <script>);
```

and so on, but all functions have arguments.

**Comment by blueloveTH** [comment]
```cpp
// A(1,2.5,5,'x')
pkpy_push_function(vm, "A(a, b, c, d)", A);
```

If you need default arguments,
```cpp
// A(1,2.5,5,'x')
pkpy_push_function(vm, "A(a=1, b=2.5, c=5, d='x')", A);
```

**Comment by carlkl** [comment]
I completely missed the signature in the documentation of pkpy_push_function. Will try that.

**Comment by blueloveTH** [comment]
Check my example of `add(a, b)` above.

**Comment by carlkl** [comment]
The add example is fine. In `main()` I fill up the stack with arguments and the C function has to consume values from the stack and returns. This is a great example to get an idea how vectorcall and the stack works.

Given this situation: 

- I want to execute (i.e. 'vm->exec()') a python script. The idea is that this python script calls C functions from a 3rd party library with given signatures. 
- So I have a function like `int A(int a, int b)` and other functions with other signatures.
- I want to call these functions with the help of the C-API of pocketpy.
- All functions arguments coming from the python script and are not known at compile time. 

It would be great to have an example like that:

```C
// simple C function
static int A(int a, int b){
    printf("A\n");
    printf("%d\n",a);
    printf("%d\n",b);
    return 0;
}
```

```python
//simple python script
A(2,3)
A(10,20)
```

Now: how to perform that with the pocketpy C-API?

**Comment by blueloveTH** [comment]
You need a wrapper to convert `int A(int a, int b)` into stack-based calls.

**Comment by carlkl** [comment]
The wrapper part for A() is easy, but the caller part (in your add example it is hard-coded in main) is non-obvious.

**Comment by blueloveTH** [comment]
```c
static int add(pkpy_vm* vm){
    int a, b;  // [<invisible> ... , 1, 2]
    pkpy_to_int(vm, -2, &a);
    pkpy_to_int(vm, -1, &b);
    pkpy_push_int(vm, f_add(a, b));  // call your external `add(int, int)` in c
    return 1;   // there is only 1 return value
}
```

**Comment by blueloveTH** [comment]
It is difficult for people without lua programming experience to understand the stack-based binding method.

Limited by the expressive power of C language, we can only do this to this extent. I admit C-APIs is difficult to use if no lua experience.

**Comment by blueloveTH** [comment]
Because pkpy is a cpp17 project. I assume users who need C-APIs are **advanced users**, so there is no beginner tutorials for C-APIs.

**Comment by carlkl** [comment]
is it possible to change the main function

```C
int main(){
    pkpy_vm* vm = pkpy_new_vm(true);
    pkpy_push_function(vm, "add(a, b)", add);    // [add]
    pkpy_push_null(vm);               // [add, <self:NULL>]
    pkpy_push_int(vm, 1);  // [add, NULL, 1]
    pkpy_push_int(vm, 2);  // [add, NULL, 1, 2]
    pkpy_vectorcall(vm, 2);  // [3]
    int x;
    pkpy_to_int(vm, -1, &x);  // [3]
    pkpy_pop_top(vm);  // []
    printf("%d\n", x);
    return 0;
}
```
with hard-coded arguments for `add` to a version which allows running a python script like this:

```python
add(1,2)
add(2,3)
...
```
Again: My problem of understanding right now is the caller, not the callee.

**Comment by blueloveTH** [comment]
You can do this in python. For example, implement a `_add(a, b)` in c, and then:
```python
def add():
  return _add(1, 2)
```

**Comment by blueloveTH** [comment]
You know you can use `exec` and `eval` to run arbitrary python code. Mixed c/python code can solve most problems.

**Comment by carlkl** [comment]
I admit, I have more questions.

"expose c functions into python globals". how to perform that with pocketpy? 

with C++ it seems to by possible to expose C++ to pocket python. Maybe this is the way to go.

**Comment by blueloveTH** [comment]
push_function + setglobal



---Original---
From: ***@***.***&gt;
Date: Tue, Aug 29, 2023 19:17 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [blueloveTH/pocketpy] C-API and bind() (Issue #128)




 
I admit, I have more questions.
 
"expose c functions into python globals". how to perform that with pocketpy?
 
with C++ it seems to by possible to expose C++ to pocket python. Maybe this is the way to go.

**Comment by carlkl** [comment]
`push_function + setglobal` _is_ pocketpy C-API. I would be happy to see a complete and self-contained example how to expose a standard C function to python, i.e. for https://github.com/blueloveTH/pocketpy/issues/128#issuecomment-1697150515

**Comment by blueloveTH** [comment]
I think I've given a pretty detailed guide and examples and **I cannot understand what you are asking.**

You can read the source code for whatever you want to know, not request a step-by-step teaching.

**Comment by carlkl** [comment]
I found what I was looking for at this place: https://github.com/nesbox/TIC-80/blob/main/src/api/python.c
As a conclusion I would like to state:
- I am excited about the idea and implementation of pocketpy.
- There is plenty of room for improvement in dealing with potential users.
