### ISSUE TITLE
Failed compiling release 1.1.6 with TDM-gcc

### ISSUE THREAD

**Issue by XingZhe-Li** [blueloveTH/pocketpy#129]
However , `1.1.4` works well when compiled with `TDM-gcc` . What should I do to fix this?

### Compile 1.1.6
<img width="656" alt="Failed" src="https://github.com/blueloveTH/pocketpy/assets/84391004/b6e58a31-4f96-419b-9976-671bc60f4496">

### Compile 1.1.4
<img width="540" alt="Success" src="https://github.com/blueloveTH/pocketpy/assets/84391004/1b983b09-84de-4864-9272-63f296b75817">

### error message:
```
C:/ProgramEnv/gcc/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\ADMINI~1\AppData\Local\Temp\cc0NVBNz.o:main.cpp:(.text+0x41076): undefined reference to `fread_s'
collect2.exe: error: ld returned 1 exit status
```

**Comment by blueloveTH** [comment]
You are right. On windows I assume you are using MSVC compiler, so `fopen_s` is used instead of `f_open`.

你是对的，在windows上我假设你使用 MSVC 编译器，因此打开文件的函数是 `fopen_s`，该函数在其他编译器上不起作用。

**Comment by blueloveTH** [comment]
I've pushed a fix for this issue. It should work now.

我推送了此 issue 的一个修复，他应该有用。
