### ISSUE TITLE
Incorrect return value for `exec` in documentation

### ISSUE THREAD

**Issue by stautonico** [blueloveTH/pocketpy#135]
I was reading through the documentation, specifically [this page](https://pocketpy.dev/quick-start/exec/#execute-python-code) and noticed that it says that `exec` returns a `PyObject*`, but it does not.

![image](https://github.com/blueloveTH/pocketpy/assets/36276517/ab8a2481-f5a1-45f1-853f-1a2708ee982f)

**Comment by blueloveTH** [comment]
i may change it to return `PyObject*` because `nullptr`.
