### ISSUE TITLE
Bind native function referencing "this"?

### ISSUE THREAD

**Issue by stautonico** [blueloveTH/pocketpy#136]
Hello. I'm trying to bind a native class function to python. However, I think I need to capture `this`, which it doesn't seem to let me do.

Here is what I'm trying to achieve:

```c++
  m_vm->bind(m_vm->_main, "testfunction(msg: str) -> None",
             [](VM *vm, ArgsView args) {
               auto msg = CAST(const char *, args[0]);
               this->_print(msg);

               return vm->None;
             });
```
however, when applying the capture (`[&](VM *vm, ArgsView args) {`), I get the error:

```
no matching function for call to ‘pkpy::VM::bind(pkpy::PyObject*&, const char [43], TestModule::TestNamespace::_init_builtins()::<lambda(pkpy::VM*, pkpy::ArgsView)>)’
```

Mm I missing something in the docs or can this not be achieved? I have already tried enabling `PK_ENABLE_STD_FUNCTION` in my cmake options (as suggested by another issue)

**Comment by blueloveTH** [comment]
C++ requires you to specify the capture list in `[]`.

```cpp
  m_vm->bind(m_vm->_main, "testfunction(msg: str) -> None",
             [this](VM *vm, ArgsView args) {    // [this] or [=] or [&], see c++ docs
               auto msg = CAST(const char *, args[0]);
               this->_print(msg);

               return vm->None;
             });
```

**Comment by blueloveTH** [comment]
Also, `CAST(const char *, args[0])` is unsafe and may not work as you expected. Either use:
```cpp
Str& msg = CAST(Str&, args[0]);
```
or
```
const char* msg = CAST(CString, args[0]);
```

**Comment by blueloveTH** [comment]
Oh, define `PK_ENABLE_STD_FUNCTION` in cmake does not work... Since the macro was already defined.
You need create your own `user_config.h` or change the source code directly.

```
// Whether to use `std::function` to do bindings or not
// By default, functions to be binded must be a C function pointer without capture
// However, someone thinks it's not convenient.
// By setting this to 1, capturing lambdas can be binded,
// but it's slower and may cause severe "code bloat", also needs more time to compile.
#define PK_ENABLE_STD_FUNCTION      0
```

**Comment by blueloveTH** [comment]
See https://pocketpy.dev/quick-start/config/.

**Comment by blueloveTH** [comment]
Another option is using pkpy's built-in capture system, it is much lighter than `std::function`.
```cpp
PyObject* f_obj = m_vm->bind(m_vm->_main, "testfunction(msg: str) -> None",
             [](VM *vm, ArgsView args) {
               auto msg = CAST(const char *, args[0]);

               void* this = lambda_get_userdata<void*>(args.begin());
               this->_print(msg);

               return vm->None;
             });
// capture this
PK_OBJ_GET(NativeFunc, f_obj).set_userdata(this);
```

**Comment by stautonico** [comment]
[This](https://github.com/blueloveTH/pocketpy/issues/136#issuecomment-1732558652) seemed to have fixed my issue (at least when it comes to compiling), however I can't seem to run it. Testing in just my `main` file works fine, however, this seems to cause a segfault:

```c++
// interpreter.h
class Interpreter {
public:
  Interpreter(...);

  int run(const std::vector<std::string> &args);

private:
  ...
  pkpy::VM *m_vm;
}}

// interpreter.cpp
#include <interpreter.h>

Interpreter::Interpreter(..) m_vm(new pkpy::VM(false)) {
 // I also tried doing m_vm = new pkpy::VM(false) here with no success
}
```

Something about the allocation breaks. gdb seems to indicate that it crashes on [this line](https://github.com/blueloveTH/pocketpy/blob/0f3915dd9f2c402503399648d871cc9699f5c94a/include/pocketpy/namedict.h#L59).

Following the gdb traceback shows that [this line](https://github.com/blueloveTH/pocketpy/blob/0f3915dd9f2c402503399648d871cc9699f5c94a/src/memory.cpp#L27) is the last one to run before the sigsegv occurs.

Any indication to why this may be happening?

**Comment by blueloveTH** [comment]
The information you provided was not enough to locate the error.
Please try to:
- upload a **Full Stacktrace**, from your own code line to the crash line
- upload a **Minimum Reproducible Example**

**Comment by stautonico** [comment]
I'm having a hard time getting consistent results. I tried writing a simplified version of my program and it worked fine. I then tried not creating the VM object in my class, but outside in a global scope, which worked. However, when I called vm->bind, it segfaulted with no additional context. Just ends there. Any hints to where I might be able to start looking into this. Note I have mutli-threading support enabled, but I am not using it (yet)

**Comment by blueloveTH** [comment]
You can search these marcos and set some of them to 1 in `config.h`.
```
/*************** debug settings ***************/

// Enable this may help you find bugs
#define PK_DEBUG_EXTRA_CHECK        0

// Do not edit the following settings unless you know what you are doing
#define PK_DEBUG_NO_BUILTINS        0
#define PK_DEBUG_DIS_EXEC           0
#define PK_DEBUG_CEVAL_STEP         0
#define PK_DEBUG_FULL_EXCEPTION     0
#define PK_DEBUG_MEMORY_POOL        0
#define PK_DEBUG_NO_MEMORY_POOL     0
#define PK_DEBUG_NO_AUTO_GC         0
#define PK_DEBUG_GC_STATS           0
```

First you may try just set `PK_DEBUG_EXTRA_CHECK` to 1, this is the basic debug flag.
And `PK_DEBUG_MEMORY_POOL`.
If it does not provide u more infos, you may try disable memory pool or gc and to see if it happens.



https://github.com/blueloveTH/pocketpy/blob/0f3915dd9f2c402503399648d871cc9699f5c94a/include/pocketpy/config.h#L35

**Comment by blueloveTH** [comment]
Was the crash caused by `vm->bind` itself? Or you mean somewhere else when `vm->bind` was used.

**Comment by stautonico** [comment]
As far as I can tell, `vm->bind` itself crashed. The call to `vm->bind` is the last stackframe in the debugger and my IDE pauses on the call to `vm->bind` then it segfaults.

**Comment by blueloveTH** [comment]
I see. I need a reproducible example to locate the problem. Without it, you need to debug by yourself...
Because of the complexity of C++, it is not a simple thing to debug by "guess" :/

**Comment by stautonico** [comment]
Sure, I am working on building a "realistic" (aka as close to my actual app as possible) reproducible example that has the same issue. I will post here once I have completed it.

**Comment by stautonico** [comment]
I have discovered a quirk on what may be causing this, but I haven't come up with a 100% reproducible example yet. Within my project, I have an `extern MyObject g_myobject` singleton variable placed within a header file. This object is populated by the "main" file. Whenever I try to use this global singleton object, pocketpy crashes with that strange `DoubleLinkedList::push_back` error, however, when I stop using that global singleton object, and create my singleton object only in my main file, the crash does not happen. I will try to build this into a reproducible example.

**Comment by stautonico** [comment]
Here is a repo containing my reproducible example. 

Instructions are in the readme, but I'll provide more here.

By default, the repo is in a working state, however, it doesn't use the global variable.

To case the example to crash, comment out [this line in main.cpp](https://github.com/stautonico/pocketpy-crash-reproducible-example/blob/2a5d1c844c5c11537002ea1215c5023ff9a83bd4/main.cpp#L7) and uncomment [this line in myobject.cpp](https://github.com/stautonico/pocketpy-crash-reproducible-example/blob/2a5d1c844c5c11537002ea1215c5023ff9a83bd4/myobject.cpp#L4). Then you can compile and build with cmake (`mkdir build && cd build && cmake .. && make && ./test`)

Please note that it is quite possible that this entire crash may be my own stupidity and misunderstanding of how c++ and memory management works. I am still relatively new to c++. Please be patient with me :)

**Comment by blueloveTH** [comment]
Okay~ I am going to check it.

**Comment by blueloveTH** [comment]
Well. This is expected.

```
#include "myobject.h"

// TO CAUSE THE CRASH: UNCOMMENT THE NEXT LINE AND COMMENT OUT THE LINE IN "main.cpp"
MyObject global_myobject;

MyObject::MyObject() {
  m_vm = new VM();
}
```

When you define it in global scope, it calls `MyObject::MyObject` at a time before `main()` and try to initialize the `VM` instance.

This is an undefined behaviour. Because the order in which global objects are initialized is unknown, especially when multiple compilation units are involved. pkpy's VM could access some uninitialized state and cause the crash.

What you need is "lazy initialization" if you want `VM*` to be accessed in global scope.
Usually a pointer is used for this. For example:

```cpp
MyObject* global_myobject;
```
And allocate it in `main()` function.

**Comment by blueloveTH** [comment]
Only POD types(int, float, bool and their simple structs) can be used in global scope safely.

Otherwise, use pointer.

**Comment by stautonico** [comment]
Oh my god, I cannot believe that I missed a `*`. In my original test build of this project, where I used `duktape`, I did use a global object pointer. Thanks for the correction, and I'm sorry for wasting your time

**Comment by blueloveTH** [comment]
You are welcome. Please give my repo a star~
