### ISSUE TITLE
[BUG] CAST macro explictly uses `vm` var (not in docs)

### ISSUE THREAD

**Issue by stautonico** [blueloveTH/pocketpy#137]
### Bug description
The `CAST` macro explicitly uses the `vm` variable name, which works fine in the examples, but does not work at all in any other case where your pocketpy `VM` object isn't named `vm` (class members for example). Unless I missed it, this isn't specified anywhere in the docs. There is some info about using the underlying function `py_cast`, but nothing specific about `CAST`.

### Steps to reproduce
```c++
#include <iostream>
#include "pocketpy.h"

using namespace pkpy;

auto main(int argc, char *argv[]) -> int {

  VM* m_vm = new VM(); // Emulating potentially using the var name `m_vm` which might be used as a class member name
  m_vm->exec("def testfunc(): return 127");

  auto result_obj = m_vm->eval("testfunc()");

  // Try to cast it
  auto result = CAST(int, result_obj); // This causes an error (provided below)

  std::cout << "Our result is: " << result << std::endl;

  return 0;
}
```
Compiler error:
```
In file included from main.cpp:2:
main.cpp: In function ‘int main(int, char**)’:
pocketpy.h:2731:31: error: ‘vm’ was not declared in this scope; did you mean ‘tm’?
 2731 | #define CAST(T, x) py_cast<T>(vm, x)
      |                               ^~
main.cpp:14:17: note: in expansion of macro ‘CAST’
   14 |   auto result = CAST(int, result_obj);
      |
```

To resolve this issue, either `py_cast` must be manually used, or a temporary variable with the name `vm` can be created:
```c++
#include <iostream>
#include "pocketpy.h"

using namespace pkpy;

auto main(int argc, char *argv[]) -> int {

  VM* m_vm = new VM(); // Emulating potentially using the var name `m_vm` which might be used as a class member name
  m_vm->exec("def testfunc(): return 127");

  auto result_obj = m_vm->eval("testfunc()");

  // Try to cast it
  // Temporary fix: Create a new variable called `vm`
  auto vm = m_vm;
  auto result = CAST(int, result_obj); // This now works since `vm` exists in scope

  std::cout << "Our result is: " << result << std::endl;

  return 0;
}
```

I don't believe that this is an issue necessarily, but I think it should be clarified in the docs, otherwise it would be confusing why your call to cast won't work. I don't believe this is written in the docs anywhere, but its possible that I missed it.

Another potential fix might be to just include your VM* object as an argument to the `CAST` macro.

**Comment by blueloveTH** [comment]
You suggestion is really helpful. A bunch of convenient macros in pkpy assumes users are using conventional names.
+ `VM* vm`
+ `PyObject* mod`
+ `PyObject* type`

```cpp
#define VAR(x) py_var(vm, x)
#define CAST(T, x) py_cast<T>(vm, x)
#define _CAST(T, x) _py_cast<T>(vm, x)

#define CAST_F(x) py_cast<f64>(vm, x)
#define CAST_DEFAULT(T, x, default_value) (x != vm->None) ? py_cast<T>(vm, x) : (default_value)
```

And you are right, there is no doc explicitly mentioned this, unless you look at the codebase via IDE's intellisense carefully.

`py_cast<T>` and `_py_cast<T>` are things you need to use if you don't use pkpy's conventional names.

**Comment by blueloveTH** [comment]
Maybe I should use `py_cast<T>` for docs and let macros be hidden.

**Comment by stautonico** [comment]
Using the IDE solved the issue for me. I was thinking to add two macros instead, one that uses the conventional names, and one that takes your own VM object, but I feel like that might be even more confusing. I think the part that is confusing here is the fact that inside a `vm->bind()`, it works fine since the lambda function has its own param named `vm`, but outside of that, since I'm using `m_vm` for my VM variable, it ceases to function. Idk what you or others might say, but my personal opinion would be to simply take the VM object as a param in the macro.

**Comment by blueloveTH** [comment]
In fact, users need `py_cast<T>` but not macros. When someone wants to customize a cast for a new cpp class.
```cpp
template<>
MyClass py_cast<MyClass>(VM* vm, PyObject* obj){
    // ...
}
```

**Comment by stautonico** [comment]
Exactly what I did. I think the macros are convenient for `vm->bind`, but not much else.
![image](https://github.com/blueloveTH/pocketpy/assets/36276517/10ac564f-61d9-49c1-9b01-03571b25bdc3)

**Comment by blueloveTH** [comment]
Some more advice here:

I know people use `VM` as a class member. I suggest to subclass `VM`.
**If you subclass `VM`, you can easily get the extra fields from the native function in bindings**

```cpp
class MyVM: public VM{
    int extra;
};

MyVM* vm = new MyVM();
vm->bind(..., [](VM* _vm, ArgsView args){
    MyVM* vm = (MyVM*)_vm;   // just a simple cast here
    int extra = vm->extra;
    return VAR(extra);
}
```

Otherwise, you need complicated "capturing" or `std::function`.

**Comment by blueloveTH** [comment]
I am updating the docs to remove macro usages.
