### ISSUE TITLE
[Feature] Better `str.format`

### ISSUE THREAD

**Issue by blueloveTH** [blueloveTH/pocketpy#138]
## Description

Python's `str` has a method named `format` documented on https://docs.python.org/3/tutorial/inputoutput.html#the-string-format-method.

Currently, the `str.format` of pkpy was [written in python at here](https://github.com/blueloveTH/pocketpy/blob/cf7dc098a3c719f6825e1d4e68729ff0ec7a37dd/python/builtins.py#L99). It is too simple to fit users' needs.

A better `str.format` implementation is required.

## Our goal

The new `str.format(*args, *kwargs)` will pass the following tests with *acceptable performance*.

```python
# support basic {}
print('We are the {} who say "{}!"'.format('knights', 'Ni'))
# We are the knights who say "Ni!"

# support {0} {1} usages
print('{0} and {1}'.format('spam', 'eggs'))
# spam and eggs

# support unordered {1} {0} usages
print('{1} and {0}'.format('spam', 'eggs'))
# eggs and spam

# support keyword arguments
print('This {food} is {adjective}.'.format(food='spam', adjective='absolutely horrible'))
# This spam is absolutely horrible.
```

It can be implemented in c++ or python.

**Comment by numan947** [comment]
Is this still open? I want to give it a try. Please assign it to me if it's still up for grabs. Thanks.

**Comment by blueloveTH** [comment]
Good luck! @numan947
