### ISSUE TITLE
[Feature] Implement `deque` in C++

### ISSUE THREAD

**Issue by blueloveTH** [blueloveTH/pocketpy#139]
## Description

`deque` is a data structure in python's `collections` module, documented on https://docs.python.org/3/library/collections.html#collections.deque.
It is used in basic algorithms such as BFS (broad-first search).

Currently, pkpy's `deque` was written in pure python at [here](https://github.com/blueloveTH/pocketpy/blob/cf7dc098a3c719f6825e1d4e68729ff0ec7a37dd/python/collections.py#L7). It is not efficient enough.

## Our goal

Move the implementation of `deque` into c++, if possible.
It is allowed to use mixed python and c++ code.

**Comment by RajdeepDey010** [comment]
hi @blueloveTH , I find this problem can be solved.
Can I get myself assigned to it.
thankyou!

**Comment by blueloveTH** [comment]
Yes, you can!

**Comment by blueloveTH** [comment]
Hello, it seems you are not working on this issue by either fork/star/pr.

So I have cancelled the assignment and leave the chance to new contributors.

**Comment by plon-Susk7** [comment]
Hi @blueloveTH I'd love to work on this issue. Please assign me.

**Comment by blueloveTH** [comment]
> Hi @blueloveTH I'd love to work on this issue. Please assign me.

This task is not easy. Do you think you have enough time to get familiar with pkpy's c++ bindings?

**Comment by numan947** [comment]
@blueloveTH, as I already have completed my previously assigned task, I would love to work on this issue for a few days. Please let me know, if @plon-Susk7 doesn't work on this.

**Comment by plon-Susk7** [comment]
Hi @numan947,
You can go ahead and work on this.

**Comment by blueloveTH** [comment]
Wish you good luck! @numan947 

I think you can implement a `LinkedList`(with minimum interfaces) to builtins and wrap it as `deque` in `python/collections.py`.

**Comment by blueloveTH** [comment]
The biggest problem of `deque` in python is its `_LinkedListNode` is an object. When users do BFS via `deque`, lots of `_LinkedListNode` objects will be created and destroyed. **They become garbages quickly.**
