### ISSUE TITLE
CS0656 when using .NET Standard 2.1 in Unity

### ISSUE THREAD

**Issue by nonperforming** [blueloveTH/pocketpy#14]
```
Assets\PocketPy\FFI.cs(27,52): 
error CS0656: Missing compiler required member 'Microsoft.CSharp.RuntimeBinder.CSharpArgumentInfo.Create'
```

Reproducible by creating an empty 3d project in Unity 2021.3.15f1 and importing PocketPy from the Asset Store.
Setting the 'Api Compatibility Level' option in Player settings from .NET Standard 2.1 (default) to .NET Framework fixes this error.

The code referenced:
```cs
static object invoke_f_any(string s)
{
    var parts = s.Split(' ');
    List<dynamic> args = new List<dynamic>();
    for (int i = 1; i < parts.Length; i++) args.Add(parse(parts[i]));
    var f = mappings[parts[0]];
    return f.DynamicInvoke(args.ToArray());
}
```

I believe it could be related to List args being dynamic

- https://forum.unity.com/threads/using-the-dynamic-keyword-in-unity-possible.496321/
- https://answers.unity.com/questions/1622645/using-dynamic-keyword.html
- https://docs.unity3d.com/Manual/dotnetProfileSupport.html

**Comment by blueloveTH** [comment]
Yes! It requires .NET 4.0 backend with `dynamic` support.
I am going to mention this in the documentations.

**Comment by blueloveTH** [comment]
I think il2cpp may not support the dynamic feature either. I need to investigate this further. If it is not supported, some advanced features can be disabled.

**Comment by blueloveTH** [comment]
`v0.8.6` has fixed this.

**Comment by nonperforming** [comment]
Thank you!
