### ISSUE TITLE
[Feature] Division algorithm for `long` object

### ISSUE THREAD

**Issue by blueloveTH** [blueloveTH/pocketpy#142]
## Description

pkpy has its special `long` object for arbitrary sized integers. See https://pocketpy.dev/features/long/.
`long` uses `list` of compressed digits as representation. 
However, division operation between two `long` objects has not been properly implemented. (I am not an expert of algorithm)

https://github.com/blueloveTH/pocketpy/blob/main/python/_long.py#L102

```python
def ulong_divmod(a: list, b: list):
    q = [0]
    while ulong_cmp(a, b) >= 0:
        ulong_inc_(q)
        a = ulong_sub(a, b)
    return q, a
```

## The goal

Write a new `ulong_divmod(a: list, b: list)` to replace the old one, adoping a more efficient division algorithm, maybe of O(N) or O(NlogN) complexity.

Also you can try optimize additional parts or give me suggession, if you think there is more improvement.

**Comment by numan947** [comment]
Could you please assign this to me?

**Comment by blueloveTH** [comment]
I think you are already working on #138 . What about leaving this to a new contributor :D

**Comment by Snehaaa18** [comment]
can you please assign me this?

**Comment by blueloveTH** [comment]
Good luck! @Snehaaa18

**Comment by blueloveTH** [comment]
Hello, it seems @Snehaaa18 are not working on this issue by either fork/star/pr.

So I have cancelled the assignment and leave the chance to new contributors.

**Comment by pranavjainjs** [comment]
Hi, I'd like to work on this issue.

**Comment by blueloveTH** [comment]
Good luck. @pranavjainjs
