### ISSUE TITLE
[Feature] Add cJSON as new JSON backend

### ISSUE THREAD

**Issue by blueloveTH** [blueloveTH/pocketpy#143]
## Description

pkpy supports `json` module with two functions.
+ `json.dumps(o: object) -> str`
+ `json.loads(s: str) -> object`

https://pocketpy.dev/modules/json/

This feature was supported by the internal python parser, which is not special designed for JSON.
So pkpy's `json` module is "3-5x" slower than other JSON libraries.

## The goal

[cJSON](https://github.com/DaveGamble/cJSON) is a widely adopted JSON library, which is stable and fast.
We want to add a new module `cjson` which provides the two functions above as an alternative JSON backend.

Also need some profile to show how fast cJSON is, comparing with the old JSON backend.

**Comment by mahbubalamdev** [comment]
Hello, I would like to work on this issue.

**Comment by blueloveTH** [comment]
Good luck! @mahbubalamdev 

Some tips:
1. If you are on linux, you can run bash build.sh to directly compile the project, which is convenient than CMake for dev.
2. Based on 1, you can run `python scripts/run_tests.py` to run unittests.

**Comment by blueloveTH** [comment]
Hello @mahbubalamdev , you need to fork the repo and open a pr to indicate you are working on it.
If you don't have time for it, please unassign youself so we can leave the chance to new contributors.

**Comment by mahbubalamdev** [comment]
@blueloveTH thanks. I'm working on it. Tonight I'll create a draft pull request.

**Comment by blueloveTH** [comment]
Completed by #151
