### ISSUE TITLE
[Feature] Support binary literals such as `0b11`

### ISSUE THREAD

**Issue by blueloveTH** [blueloveTH/pocketpy#145]
## Description

pkpy does not support binary literials such as `0b11`.
But it supports hex literials such as `0xff`.

## The goal

Add some more thing into the parser to make it support binary literials.

```python
a = 0b00
b = 0b10
c = 0b111100
d = 0bff  # syntax error
# syntax error
e = 0b11111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111
```

1. Raises syntax error if it is not a valid binary literial.
2. Raises syntax error if the number cannot be represented in 64-bit.

**Comment by LeidiFlores** [comment]
Hello!

I want to work on this, could you please assign it to me?

**Comment by blueloveTH** [comment]
Good luck! @LeidiFlores 

Some tips:
1. If you are on linux, you can run bash build.sh to directly compile the project, which is convenient than CMake for dev.
2. Based on 1, you can run `python scripts/run_tests.py` to run unittests.

**Comment by blueloveTH** [comment]
Hello @LeidiFlores , you need to fork the repo/pr to indicate you are working on it.
If you don't have time for it, please unassign youself so we can leave the chance to new contributors.

**Comment by LeidiFlores** [comment]
@blueloveTH yes! sorry, I'm on it !

**Comment by blueloveTH** [comment]
Close it because of https://github.com/blueloveTH/pocketpy/pull/154 was almost done.
