### ISSUE TITLE
[Feature] Support octal literals such as "0o644"

### ISSUE THREAD

**Issue by stautonico** [blueloveTH/pocketpy#146]
# Description

pkpy doesn't support octal literals such as 0o644, but it supports hex literals such as 0xff.

# The goal

Add some more thing into the parser to make it support octal literals.

```py
a = 0o644
b = 0o1337
c = 0oFF  # SyntaxError: invalid octal literal
```

**Comment by blueloveTH** [comment]
Do you want to join hacktoberfest2023 and take this #145 ? @stautonico

**Comment by stautonico** [comment]
Its a nice idea, but I think I'm to unfamiliar with c++ to work on a project as complex as this. Its a pretty highly likely chance that I'll either pump out a buggy mess, or end up not finishing it at all. Maybe sometime in the future :/
