### ISSUE TITLE
[Feature] : Success/error comments in build.sh file.

### ISSUE THREAD

**Issue by pranavjainjs** [blueloveTH/pocketpy#147]
**The problem**
On running `bash build.sh` there is no output shown in the terminal. How would a developer know if it ran successfully? If it ran at all?

**Proposed solution**
A success/failure message for build.sh

**Comment by pranavjainjs** [comment]
I can work on this issue if it's fine.

**Comment by blueloveTH** [comment]
Sure, you can have a try.
