### ISSUE TITLE
'Supported Platforms' architecture in README.md

### ISSUE THREAD

**Issue by nonperforming** [blueloveTH/pocketpy#153]
Currently, 'Supported Platforms' section in README.md shows these platforms as supported.

- Windows 64-bit
- Linux 64-bit / 32-bit
- macOS 64-bit
- Android 64-bit / 32-bit
- iOS 64-bit
- Emscripten 32-bit
- Raspberry Pi 64-bit

Especially for platforms like macOS, it should be marked whether it is x86-64 (or x64 for short, Intel) or AArch64 (or ARM64 for short, pple Silicon, M1/M2) and for specific versions of Windows/Android/etc. 

Additionally, 'Raspberry Pi' should most likely be 'Raspberry Pi OS' - and preloaded OS on Raspberry Pi (which is ARM64 or AArch64 or more recent Pis) is 32 bit and user needs to flash 64 bit image themselves iirc. What distro (and version of distro) being used should also be included in Linux.

A table would also have nicer formatting in my opinion.

## Example

| Operating System | Operating System Version | Architecture | PocketPy Version |
|------------------|--------------------------|--------------|------------------|
| Windows 10 | 10.0.19045.3516 | x86-64 | v1.2.2 |
| Ubuntu | 22.04 | x86-64 | v1.2.2 |
| macOS | Sonoma (14.1 beta 2) | x86-64, AArch64 | v1.2.2 |
| Raspberry Pi OS | May 3rd 2023 | AArch64 | v1.2.2 |

## Also see:
https://en.wikipedia.org/wiki/X86
https://en.wikipedia.org/wiki/X86-64
https://en.wikipedia.org/wiki/AArch64

**Comment by blueloveTH** [comment]
Well, I use 32-bit/64-bit because there is some difference in it.

However, pkpy don't care architecture as long as you have a C++17 compiler.

Also, the table is not "supported platforms", instead, they are "tested platforms" which is a subset of supported platforms.

Raspberry Pi OS makes sense.
