### ISSUE TITLE
Build instructions on README.md and build.sh assumes Debian/Ubuntu distribution

### ISSUE THREAD

**Issue by nonperforming** [blueloveTH/pocketpy#158]
Also, strangely enough, I couldn't find the package `clang++` in Debian or Ubuntu package search... @blueloveTH what Linux distribution are you using to build?

**Comment by blueloveTH** [comment]
I am using WSL with ubuntu.

**Comment by numan947** [comment]
@blueloveTH, I think I pointed to the wrong package when I told you about clang++ installation. Apparently, `clang++` is part of `clang`, and it gets automatically installed when you run the command: `sudo apt-get install clang`
