### ISSUE TITLE
`dir("s")` gives segfault

### ISSUE THREAD

**Issue by gacheiro** [blueloveTH/pocketpy#16]
Hello, I was playing with the REPL and when I type the following code, it gives segmentation fault:

```
>>> dir("s")
[1]    144790 segmentation fault (core dumped)  ./pocketpy
```

And this one as well:

```
>>> s = "s"
>>> dir(s)
[1]    144790 segmentation fault (core dumped)  ./pocketpy
```

I only got this error when using `dir` with strings, it seems to work properly for other types.

**Comment by blueloveTH** [comment]
Yeah, it is true! I know the reason and will fix it later.

**Comment by blueloveTH** [comment]
Yeah, I know the reason and will fix it later.
