### ISSUE TITLE
Create CONTRIBUTING.md File

### ISSUE THREAD

**Issue by vatsalya-vyas** [blueloveTH/pocketpy#160]
# Description 

The goal of a CONTRIBUTING.md file is to increase the number of successful contributors to your project.

A great contributing guide will:

- Demonstrate to new contributors that your project has a good contributor experience.

- Improve the quality of contributions to your project.

- Make your developer documentation more discoverable.

**Comment by vatsalya-vyas** [comment]
Can you assign the issue to me, please?

**Comment by blueloveTH** [comment]
I think you can directly submit something and let me know what you want to add.

**Comment by vatsalya-vyas** [comment]
Would you please label this issue for Hacktoberfest?
