### ISSUE TITLE
[Integration] Publish pocketpy to vcpkg

### ISSUE THREAD

**Issue by blueloveTH** [blueloveTH/pocketpy#163]
## Description

[vcpkg](https://github.com/microsoft/vcpkg) is a cross-platform package manager for C and C++ developers.
It would be useful for users if they can install pocketpy via it.

## Our goal

1. Make necessary changes and submit pocketpy to vcpkg.
2. Add document about how to install pocketpy via vcpkg.

**Comment by namit343** [comment]
Hey, I figured out how to publish this package on vcpkg, you have to open a new PR at https://github.com/microsoft/vcpkg

**Comment by blueloveTH** [comment]
Yes. You will (replace me) submit that PR at https://github.com/microsoft/vcpkg and add docs into pocketpy repo.
