### ISSUE TITLE
[Integration] Publish pocketpy into conan

### ISSUE THREAD

**Issue by blueloveTH** [blueloveTH/pocketpy#164]
## Description

[conan](https://github.com/conan-io/conan) is a cross-platform package manager for C and C++ developers.
It would be useful for users if they can install pocketpy via it.

## Our goal

1. Make necessary changes and submit pocketpy to conan.
2. Add document about how to install pocketpy via conan.

**Comment by Cretus-iosDev** [comment]
hi @blueloveTH I want to contribute to this.
can you please tell me more about the 1st point? 
which is  - "Make necessary changes and submit pocketpy to conan."

the  2nd point i understood

**Comment by Cretus-iosDev** [comment]
@blueloveTH  please tell more about the 1st point

**Comment by blueloveTH** [comment]
You will (replace me) submit a recipe PR to https://github.com/conan-io/conan-center-index and add docs into pocketpy repo.
