### ISSUE TITLE
[Feature] Is it possible to make pocketpy compatible with the Qt build environment?

### ISSUE THREAD

**Issue by ldraconus** [blueloveTH/pocketpy#167]
If I include pocketpy.h in my Qt project, I run into two name collisions:

1. emit method (used in the Qt message passing)
2. METHOD macro (not sure, but it collides with something)

A good solution (in my opinion) is:

```
#if defined(QT_VERSION)
#define emit emit_
#endif
```
and where the METHOD macro is defined can it simply be changed to METHOD_ automagically in the build script?

or possibly put that whole section in another if-defined block and used METHOD_ instead.  Possibly a define changing the define, but I'm not entirely sure if that would work... depends on the preprocessor.  It /might/.

**Comment by ldraconus** [comment]
This works for me on linux:

```
#if defined(QT_VERSION)
#undef emit
#define emit emit_
#undef METHOD
#endif
```

**Comment by ldraconus** [comment]
... and you could probably even emit (get it) the #define of emit, come to think of it

**Comment by blueloveTH** [comment]
Hi, I've pushed a commit to fix `METHOD()` https://github.com/blueloveTH/pocketpy/commit/f3acafe44c523f0275fef5ead8e32df1ed6fb364.

**Comment by blueloveTH** [comment]
I am not sure this is safe.
```cpp
#if defined(QT_VERSION)
#define emit emit_
#endif
```

So you can have your own fix.

**Comment by blueloveTH** [comment]
I've replaced all `emit` into `emit_` in https://github.com/blueloveTH/pocketpy/commit/901f702f00d25cdbae466ded1632a833bbbda5f6.

Please try the latest commit.
