### ISSUE TITLE
[Docs] Design some examples for beginners

### ISSUE THREAD

**Issue by blueloveTH** [blueloveTH/pocketpy#168]
## Description

pkpy need some live examples to be complementary with documents.
These examples can help beginners who likes code.

## The goal

Create a directory named "examples" in the root, add 5 cpp files.

Each cpp file is an example with a meaningful filename that shows some functionality of pkpy's usages (e.g. run python code, call python functions, do cast and bindings).

The example code should be well-commented.

**Comment by mahbubalamdev** [comment]
@blueloveTH I would like to work on this issue. Could you please assign it to me? Thanks.
