### ISSUE TITLE
`pkpy` syntax errors that are valid in cpython

### ISSUE THREAD

**Issue by gacheiro** [blueloveTH/pocketpy#17]
Hello @blueloveTH,
I've been playing with `pocketpy` and here are some syntax error that are valid in cpython but not in pkpy.

1-tuple or empty tuple:

```python
(1,)     # SyntaxError
1,       # SyntaxError
()       # SyntaxError
tuple()  # TypeError
```

Empty list slice:
```python
[][:-1] # std::exception
```

One line if/function:
```python
if 1: pass    # SyntaxError
def f(): pass # SyntaxError
```

Do you think they should be valid pkpy code as well?

**Comment by blueloveTH** [comment]
- I think Empty list slice is a bug, and will be fixed.
- One line if/function is a feature that may be supported.
- 1-tuple or empty tuple does not make a lot of sense.

**Comment by blueloveTH** [comment]
1 element tuple is supported now.

**Comment by gacheiro** [comment]
Thanks for supporting this !
