### ISSUE TITLE
C-API - Referencing python instances in C

### ISSUE THREAD

**Issue by Chukobyte** [blueloveTH/pocketpy#170]
Question, is there a way to keep track of python instances using the C-API?  I'm prototyping converting my engine's cpython stuff to pocketpy, but from what I can tell the only way to do so would be to keep track of then in python.

One other unrelated question, I've noticed that when I try to provide keyword arguments for a python instance's function the following result happens?
```py
class Node:
    def __init__(self, entity_id: int):
        self.entity_id = entity_id

print(f"{Node(entity_id=1}")
# Returns 'TypeError: __init__() takes 2 positional arguments but 1 were given'
```

Does this have to do with `positional and keyword arguments are strictly evaluated`?

Great library btw, keep up the good work!

**Comment by blueloveTH** [comment]
Yes. If you want to use k=v than the argument must also be defined as k=v (i.e. it has a default value)

**Comment by blueloveTH** [comment]
I don't get it about "keep track of python instances". Could you please give an example/use case?

**Comment by Chukobyte** [comment]
> I don't get it about "keep track of python instances". Could you please give an example/use case?

I want to map entities within my engine to python instances so that I can reference the instances later to call functions, inspect properties, etc...  For example, I create a new `Node` instance like:
```c
// vm already initialized
pkpy_getglobal(vm, pkpy_name("Node"));
pkpy_push_null(vm);
pkpy_push_int(vm, 1);
pkpy_vectorcall(vm, 1);
```

That will put a new instance of `Node` on the top of the stack correct?  I would like to somehow store this instance so I can use later for callbacks that exist on the python instance:
```c
// After creating instance
PyObject* pyInst;
pkpy_to_pyobj(vm, 0, pyInst);

// When we need to use the instance (e.g. calling a method)
PyObject* pyInst = game_engine_get_py_inst(entityId);
pkpy_push_pyobj(vm, pyInst);
// Do stuff with instance
```

From what I can tell I could do something like store a global dict of nodes in python:
```py
GLOBAL_ENTITIES_MAP: Dict[int. Node] = {} 
``` 

But I would like to limit the usage of python in the engine directly unless I need to.

**Comment by blueloveTH** [comment]
You can use `pkpy_setglobal`, this set the top of the stack (your Node instance) as a global variable. Then you can use `pkpy_getglobal` to access its value.

**Comment by blueloveTH** [comment]
C-API does not allow to store `PyObject*` directly. It is a stack-based API.

If you like non-stack-based style, you can use C++ API.

**Comment by Chukobyte** [comment]
I was thinking that was the case but wanted to be sure before I continued on with adding pocketpy to my project.  Thanks for your time!
