### ISSUE TITLE
Context Block: __enter__ custom values

### ISSUE THREAD

**Issue by pmp-p** [blueloveTH/pocketpy#187]
I noticed a different behaviour from other pythons in context blocks here :
```
class Test:
    def __enter__(self):
        return "custom"
    def __exit__(self, *argv):
        ...
with Test() as custom_as:
    assert(custom_as == "custom")
print(custom_as)
```
it seems "as" does not alias the return value of `__enter__`.

**Comment by blueloveTH** [comment]
Okay.

**Comment by blueloveTH** [comment]
No plan to change this behaviour. I'd recommend users to return self in `__enter__`.
