### ISSUE TITLE
Compatibility with nanobind python modules?

### ISSUE THREAD

**Issue by rjklindsay** [blueloveTH/pocketpy#189]
Nanobind is used to wrap C++ code and create Python modules.
However, these modules can also be called from Javascript, Lua, Ruby, C++ and other languages that can interface with C API's.
Details regarding the function’s parameters and return value are automatically inferred using template metaprogramming, which makes nanobind's syntax more compact and elegant, compared to pocketpy's current module binding mechanism.
Are there any plans to support Python modules created with nanobind?

See: [nanobind library](https://github.com/wjakob/nanobind)

**Comment by blueloveTH** [comment]
pkpy's binding is low-level and of max performance. It is not conflict with high level binding solution such as pybind11 or nanobind you mentioned.

I am focusing on providing a feature complete low-level bindings and leaving others to the community. If you are the contributor of nanobind and want to create a nanobind like solution for pkpy, I am glad to cooperate with you.
