### ISSUE TITLE
[BUG] Parsing issue in subscript with slices and multidimensional indices

### ISSUE THREAD

**Issue by qtnc** [blueloveTH/pocketpy#192]
Hello,

I was trying to implement a 2D grid, and I found a bug in parsing subscript and slices when using multidimensional indices.

Let's take this python code:

    class grid:
      def __getitem__ (self, arg):
        print(arg)
    
    g = grid()
    x = g[1:2, 3:4]

Result printed with original CPython:  
`(slice(1, 2, None), slice(3, 4, None))`

Result printed with pocketpy:  
`slice(1, (2, 3), 4)`

Additionally, orriginal CPython perfectly accepts `g[1:2:3, 4:5:6]`, while pocketpy rejects it with a syntax error.

2D grids can be quite useful in games, and it's certainly better if we can use all the power of natural python syntax...

Would you prefer fixing it yourself, or let me first trying to make a PR?

Thank you.

**Comment by blueloveTH** [comment]
Thanks for reporting. I think this is a bug and I will try to fix it.



---Original---
From: ***@***.***&gt;
Date: Sat, Dec 30, 2023 05:57 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: [blueloveTH/pocketpy] [BUG] Parsing issue in subscript with slicesand multidimensional indices (Issue #192)




 
Hello,
 
I was trying to implement a 2D grid, and I found a bug in parsing subscript and slices when using multidimensional indices.
 
Let's take this python code:
 class grid:   def __getitem__ (self, arg):     print(arg) g = grid() x = g[1:2, 3:4]  
Result printed with original CPython:
 (slice(1, 2, None), slice(3, 4, None))
 
Result printed with pocketpy:
 slice(1, (2, 3), 4)
 
Additionally, orriginal CPython perfectly accepts g[1:2:3, 4:5:6], while pocketpy rejects it with a syntax error.
 
2D grids can be quite useful in games, and it's certainly better if we can use all the power of natural python syntax...
 
Would you prefer fixing it yourself, or let me first trying to make a PR?
 
Thank you.

**Comment by blueloveTH** [comment]
Hi @qtnc After a deeper look of our slice parsing mechanism. I found it is not possible to have 2 slice object in a single subscription. The parsing always convert all items inside a `[]` into a single `slice` object so your demo is not possible currently. There is no simple fix.

I will keep this issue open until I think it is the time to do refactor.

**Comment by blueloveTH** [comment]
You can try another way for multi-dim use case. For example:
```
grid[1:2][3:4]
```

**Comment by blueloveTH** [comment]
Also, I see you have submitted many issues these days. I invite you to join our Discord https://discord.gg/WWaq72GzXv if you haven't. I am glad to know more about your games/engines. In this way, I can re-estimate the priority of satisfying your needs.
