### ISSUE TITLE
`__getattr__`

### ISSUE THREAD

**Issue by apsz3** [blueloveTH/pocketpy#22]
Will `__getattr__` be available for overriding? Would this amount to binding the CPP method when classes are instantiated?

**Comment by blueloveTH** [comment]
In fact, I haven't figured out how to make a convenient cpp binding interface. Although the current interface is OK, it is relatively primitive. For example, you need to handle the conversion of PyObject and C type manually, while pybind11 can handle it automatically.

**Comment by blueloveTH** [comment]
In fact, I haven't figured out how to make a convenient cpp binding interface. Although the current interface is OK, it is relatively primitive. For example, you need to handle the conversion of PyObject and C type manually, while pybind11 can handle it automatically.

**Comment by blueloveTH** [comment]
There is not a way to override `__getattribute__`. Because I think it is not frequently-used.
If `__getattribute__` exists, we need to do an extra check and cause a little performance loss.

**Comment by blueloveTH** [comment]
I have two ideas to make CPP bindings easily.

1. adopt template meta-programming (TMP) just like pybind11 does. But it is very hard. I am not familiar with TMP.
2. Write a moc (meta object compiler) in Python, moc is able to analyze the source code and generate primitive bindings automatically.

**Comment by blueloveTH** [comment]
> I have two ideas to make CPP bindings easily.
> 
> 1. adopt template meta-programming (TMP) just like pybind11 does. But it is very hard. I am not familiar with TMP.
> 2. Write a moc (meta object compiler) in Python, moc is able to analyze the source code and generate primitive bindings automatically.

Well. There is a main difference between cpython and pkpy. cpython does not support multi-vm, its vm is in global namespace so static TMP works. However, in pkpy, bindings are connected to a specific vm (dynamically allocated). TMP may not easy to impl.

**Comment by blueloveTH** [comment]
`__getattr__` and `__setattr__` are plan to impl now.
