### ISSUE TITLE
Support for the walrus operator

### ISSUE THREAD

**Issue by gacheiro** [blueloveTH/pocketpy#23]
Would be cool to have support for the walrus operator 😁

**Comment by apsz3** [comment]
So I actually started work on an implementation of this. I will make a draft PR. It isn't totally complete because I can't figure out some grammar ambiguity.

**Comment by blueloveTH** [comment]
I'm not sure that this feature is necessary. Some people think that the use of walrus operator reduces readability and it often makes a line of code longer.
It relates to [PEP 572](https://peps.python.org/pep-0572/), which is a controversial proposal at that time.

Personally, I don't encourage using it, but we may implement it for compatibility reasons. It depends on the frequency of use of this feature in existing python modules.
