### ISSUE TITLE
[BUG] `exit()` calls `std::exit()` instead of raising a `SystemExit`

### ISSUE THREAD

**Issue by ghost** [blueloveTH/pocketpy#250]
### Bug description

When calling `exit()` in Python code, it will immediately exit the parent process instead of throwing a `SystemExit` like CPython. This is a problem for in-game scripting because it gives the user an opportunity to inadvertently crash the game.

### Steps to reproduce

```c
VM* vm = new VM();
try {
    vm->exec("exit(42)");
} catch (const pkpy::Exception &e) {
    print("Whoopsie")
}
print("This happens after the VM exits.")
```

The program will terminate with exit code 42 without printing any additional messages.

### Environment information

main branch, OS is not relevant.

### Additional context

It is possible to override this behavior by rebinding the `exit()` function as follows:

```c
bind(builtins, "exit(code=0)", [](pkpy::VM* vm, pkpy::ArgsView args) {
    // Do something here
    return vm->None;
});
```

I'd be happy to contribute a fix as follows:

1. Define a `SystemExit` exception and make the `exit(code=0)` Python function raise it.
2. The `void exit()` function should catch the `SystemExit` exception and use `std::exit` for compatibility. (Alternatively we could break backwards compatibility because this behavior is unlikely to be used in anything but trivial examples.)
3. Add a new `int exec_with_return_code()` function which returns the exit code as intended.
4. When calling `_exec` on a `CodeObject_`, the returned `pkpy::PyVar` should contain an integer with the exit code.

Please let me know if you want me to work on this.

**Comment by blueloveTH** [comment]
I don't want to change this. If you are unhappy about default "exit", we recommend you to delete/replace it.
