### ISSUE TITLE
optimiazte emhash8

### ISSUE THREAD

**Issue by ktprime** [blueloveTH/pocketpy#29]
you can define maco EMH_WYHASH_HASH before including head file hash_table8.hpp
which is more efficient than std::hash<string>

**Comment by blueloveTH** [comment]
Thanks for your advice.

As for now, there is a new class `StrName` which does pooling for all identifiers. So we don't need to hash `std::string` anymore.

`emhash8::HashMap<StrName, PyVar>`

`StrName` is a 32 bit integer. So I'd like to find a special hash for this case.

`StrName` is

**Comment by blueloveTH** [comment]
Currently there is a huge overhead in function call.

When doing a call like `f(x, y, z)`, we need to new a hashmap to store locals. And the locals will soon be freed when function returns.

For this case, I think the hashmap can be optimized for storing 0-8 elements(regular argument numbers of a function call) and it has fast new/delete performance.

**Comment by blueloveTH** [comment]
I saw you have mentioned a stack hashmap in the docs. I want both of them~

1. a lightweight hashmap for function call(fast new/delete)
2. a heavy hashmap for __dict__(fast lookup but we don't care new/delete)

**Comment by ktprime** [comment]
now only emhash5 support small hashmap,
you can try it by define EMH_SMALL_SIZE = 8

**Comment by ktprime** [comment]
#define EMH_FIND_HIT can improve finding hit performance(10%) in emash5/6

**Comment by blueloveTH** [comment]
> now only emhash5 support small hashmap, you can try it by define EMH_SMALL_SIZE = 8

That's awesome. What happens if adding more than 8 elements with EMH_SMALL_SIZE=8.

**Comment by ktprime** [comment]
if size > EMH_SMALL_SIZE, it will alloc heap memory and copy stack memory to heap.

**Comment by ktprime** [comment]
![image](https://user-images.githubusercontent.com/1461362/220278375-bea29f8e-3e93-4e1e-8029-c6c1d09c8a1d.png)

**Comment by blueloveTH** [comment]
Great. I also have an idea to implement a very customized version, focusing on `<int32, PyVar>`.

**Comment by ktprime** [comment]
> Great. I also have an idea to implement a very customized version, focusing on `<int32, PyVar>`.
> 
> For example, I want to pre-make some hashmap that sizes 8, 16, 32. When needed, we can just retrieve one from the pool.

but emhash5 is used a fixed marco value, so need change it to be a template arg

**Comment by blueloveTH** [comment]
https://github.com/python/cpython/blob/main/Objects/dictobject.c#L172

**Comment by blueloveTH** [comment]
> but emhash5 is used a fixed marco value, so need change it to be a template arg

Perhaps it is not the case.
I mean pre-making the underlying array, not hashmap instance. When the hashmap enlarges, it retrieve a low level array from the pool.

**Comment by ktprime** [comment]
> > but emhash5 is used a fixed marco value, so need change it to be a template arg
> 
> Perhaps it is not the case. I mean pre-making the underlying array, not hashmap instance. When the hashmap enlarges, it retrieves a low level array from the pool.
> 
> If I can access to the low level array, there is a faster way to move a bunch of `PyVar`.(a tagged pointer)

    **inline const value_type* values() const { return _pairs; }** in emhash8, key/value in a continuous array.

**Comment by ktprime** [comment]
```
emhash8<int, int> e8 = {{1,2},{2,0}};
const auto& node = *values();
for (int i = 0; i < e8.size(); i++)
  doit(node[i].first, node[i].second);
```

**Comment by blueloveTH** [comment]
Thank you~I will try!

**Comment by ktprime** [comment]
if no any deletion on emhash8, the order of nodes array just as insertion order.

**Comment by blueloveTH** [comment]
I am trying a fancy idea.

I noticed a fact that, the keys of some hashmap is already known. For example, `int` has `__add__`, `__sub__`, etc. Its keys won't change. A function locals, the keys are predefined in the symbol table. (unless one call `setattr` or `exec` to dynamically add key)

So I made a simple hashmap with some special things.
1. calulate the initial capacity with predefined keys, so the hashmap won't do expensive rehash.
2. use `find_perfect_hash_seed` to get a hash seed (get into hash function) that with no/few collision.
3. Dynamic `load_factor`, for type/module object, small load factor is used since they are not frequently new/delete. For normal objects, use standard load factor to save memory.

**Comment by ktprime** [comment]
https://github.com/renzibei/fph-table, just tiny faster than flat hash. 

https://martin.ankerl.com/2022/08/27/hashmap-bench-01/#benchmark-results-table

**A very interesting new contender: This hashmap implementation uses a perfect hash, thus it doesn’t have any collisions. This should make it extremely fast for lookups, but with a potentially high overhead for insert/removal.

The Good
Find is extremely fast, regardless of the hash. In fact, std::hash or boost::hash is best here even with their bad hash quality.
The Bad
Insert and erase and copying the map is very very slow, the slowest in the benchmark. Memory usage is very high. I’d say this map is good for stable data that is never modified, and when you can afford the high memory usage.
About
Website: https://github.com/renzibei/fph-table/tree/noseed, Tested version: 1a613aba (noseed), License: none specified**

**Comment by blueloveTH** [comment]
That makes sense. It still require some time to find perfect mapping algo.

I also changed the layout of `<KeyT, valueT>`. Normally we use `std::pair` or struct to store them.

While I use this.
```
[key0, key1, key2, ...] [val0, val1, val2, ...]
```

https://github.com/blueloveTH/pocketpy/blob/main/src/namedict.h#L19

So I can use `memset` to reset keys/values/both, instead of calling destructor.

**Comment by blueloveTH** [comment]
I also want to do these special optimizations.

1. embed ref counting into the hashmap so we don't need to use `shared_ptr` wrapper, hence reduce one heap allocation.
2. use uint16_t instead of uint32_t.
