### ISSUE TITLE
C-API: how to exchange scalar data or arrays or lists

### ISSUE THREAD

**Issue by carlkl** [blueloveTH/pocketpy#40]
Thank for this clever python alike library! This could be useful for many applications, not only gaming.

Sorry for my ignorance: What is the easiest way to exchange scalar data (float, int) beside of chars with the help of the C-API? And is there a way to exchange arrays of data of uniform data types? 

And as I'm curious: what is the meaning of `pkpy_setup_callbacks`?

I'm thinking of using pocketpy as a kind of programmable input-file for data processing.

**Comment by blueloveTH** [comment]
The C-API is designed for communicating with languages other than C/C++(as a dynamic library). There is an internal protocol to transfer basic types. But the functionality is limited.

**Comment by blueloveTH** [comment]
If you are using C or C++, just use C++ apis to do integration. `CAST` and `VAR` macros can do convert between Python objects and c types. For array, use `List`.

**Comment by blueloveTH** [comment]
But, yes, the docs are a bit misleading...

**Comment by blueloveTH** [comment]
Another solution is to get a 3rd json library.

You can use `pkpy_vm_eval` to run something and return json string and parse it via that library.

**Comment by carlkl** [comment]
For the sake of simplicity I will try some kind of serialization.
