### ISSUE TITLE
c example

### ISSUE THREAD

**Issue by shakfu** [blueloveTH/pocketpy#41]
Hi @blueloveTH 

Very cool project. Thanks very sharing!

Incidentally, I had trouble compiling the [c-example](https://pocketpy.dev/getting-started/c/#basic-example) on macOS 12.6.3 (Monterey) x86_64 without changing this line 

```c
VM* vm = pkpy_new_vm(true);
```

to 

```cpp
pkpy::VM* vm = pkpy_new_vm(true);
```
using

```bash
clang++ --std=c++17 -o demo demo.cpp
```

**Comment by blueloveTH** [comment]
Thanks for your report. It has been fixed.
