### ISSUE TITLE
pythonpath or execfile support?

### ISSUE THREAD

**Issue by shakfu** [blueloveTH/pocketpy#43]
Hi,

Thanks very much for creating this project. I'm really enjoying using your library in a [max external plugin](https://github.com/shakfu/py-js/tree/main/source/projects/pktpy), I have been working on recently:

<img width="844" alt="screanshot" src="https://user-images.githubusercontent.com/3701918/227554735-91e58c65-40df-430b-898d-aef63a2da701.png">

I'm really interested in setting the working directory for imports (like a pythonpath) or in some kind of execfile(path) support where path is python script.

Is this something already available or planned?

**Comment by shakfu** [comment]
`execfile` is quite simple to replicate. Something along the lines of:

```cpp
    std::ifstream ifs("test.py");
    std::stringstream buffer;
    buffer << ifs.rdbuf();
    vm->exec(buffer.str(), "main.py", EXEC_MODE);
    vm->exec("print(test())", "main.py", EXEC_MODE); // test func in test.py
```

importing from a user file doesn't work though... even with `#define PK_ENABLE_FILEIO 1`

**Comment by blueloveTH** [comment]
Yes, the `import` system is still under developing. The next version will support flat import from file, i.e., pure `.py` file in working directory but not folders.

**Comment by shakfu** [comment]
@blueloveTH thanks for your reply. That sounds good. Please make it possible to set the working directory for imports then. 😃

**Comment by blueloveTH** [comment]
Added `os.chdir` function to change current working directory.
In C++, you can use `std::filesystem::current_path(...)` directly. Note that working directory is shared by all VMs.

**Comment by shakfu** [comment]
@blueloveTH 

Thanks very much. I'll give it a go in my project.
