### ISSUE TITLE
First record a syntax parsing bug

### ISSUE THREAD

**Issue by XR-stb** [blueloveTH/pocketpy#50]
![image](https://user-images.githubusercontent.com/56108982/229146662-a6ad4e2c-5258-4c1e-af03-514769a68e52.png)

**Comment by blueloveTH** [comment]
Related snippet: 
https://github.com/blueloveTH/pocketpy/blob/main/web/index.js#L148

**Comment by XR-stb** [comment]
具体的原因：因为我输入了中文的句号'。' 然后在退格的时候，中文字符虽然被删除了，但是多了一个空字符，在当我也删除这个空字符后，前端终端显示的字符还存在的（实际上已经被删除了）
1.首先在变量名后输入一个中文句号
![image](https://user-images.githubusercontent.com/56108982/229292866-2e76f6eb-e4b7-4b1a-827a-b002483c8f52.png)
2.进行了一次退格（删除）操作
![image](https://user-images.githubusercontent.com/56108982/229292879-ba00b88c-fdb9-4eac-a4a2-fc5b28c70388.png)
3.再进行一次退格操作，看起来a字符还存在
![image](https://user-images.githubusercontent.com/56108982/229292906-f2de5c12-5ede-444c-9e75-a1611ebaec40.png)
4.后面接着正常赋值，会发现出现了问题
![image](https://user-images.githubusercontent.com/56108982/229292978-170d0c22-d35f-4384-aed0-f4c24ada2c3e.png)
