### ISSUE TITLE
flutter build apk Fail on Linux Ubuntu

### ISSUE THREAD

**Issue by makao007** [blueloveTH/pocketpy#54]
flutter build apk 
Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!

💪 Building with sound null safety 💪

Building with Flutter multidex support enabled.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':pocketpy:buildCMakeRelWithDebInfo[arm64-v8a]'.
> Build command failed.
  Error while executing process /home/mkw/Android/Sdk/cmake/3.18.1/bin/ninja with arguments {-C /home/mkw/.pub-cache/hosted/pub.dev/pocketpy-0.9.3/android/.cxx/RelWithDebInfo/161p5t12/arm64-v8a pocketpy}
  ninja: Entering directory `/home/mkw/.pub-cache/hosted/pub.dev/pocketpy-0.9.3/android/.cxx/RelWithDebInfo/161p5t12/arm64-v8a'
  [1/2] Building CXX object CMakeFiles/pocketpy.dir/pocketpy.cpp.o
  FAILED: CMakeFiles/pocketpy.dir/pocketpy.cpp.o 
  /home/mkw/Android/Sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ --target=aarch64-none-linux-android21 --gcc-toolchain=/home/mkw/Android/Sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/linux-x86_64 --sysroot=/home/mkw/Android/Sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/linux-x86_64/sysroot -DDART_SHARED_LIB -Dpocketpy_EXPORTS  -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security   -O2 -g -DNDEBUG -fPIC -fno-rtti -std=gnu++17 -MD -MT CMakeFiles/pocketpy.dir/pocketpy.cpp.o -MF CMakeFiles/pocketpy.dir/pocketpy.cpp.o.d -o CMakeFiles/pocketpy.dir/pocketpy.cpp.o -c /home/mkw/.pub-cache/hosted/pub.dev/pocketpy-0.9.3/src/pocketpy.cpp
  In file included from /home/mkw/.pub-cache/hosted/pub.dev/pocketpy-0.9.3/src/pocketpy.cpp:1:
  In file included from /home/mkw/.pub-cache/hosted/pub.dev/pocketpy-0.9.3/src/pocketpy.h:19:
  In file included from /snap/flutter/current/usr/include/c++/9/regex:45:
  /snap/flutter/current/usr/include/c++/9/memory:121:25: error: cast from pointer to smaller type 'uintptr_t' (aka 'unsigned int') loses information
    const auto __intptr = reinterpret_cast<uintptr_t>(__ptr);
                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  In file included from /home/mkw/.pub-cache/hosted/pub.dev/pocketpy-0.9.3/src/pocketpy.cpp:1:
  /home/mkw/.pub-cache/hosted/pub.dev/pocketpy-0.9.3/src/pocketpy.h:5353:54: error: cast from pointer to smaller type 'uintptr_t' (aka 'unsigned int') loses information
          std::uintptr_t addr = self.is_tagged() ? 0 : (uintptr_t)self.get();
                                                       ^~~~~~~~~~~~~~~~~~~~~
  2 errors generated.
  ninja: build stopped: subcommand failed.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 7s
Running Gradle task 'assembleRelease'...                            8.5s
Gradle task assembleRelease failed with exit code 1

**Comment by blueloveTH** [comment]
Seems like there is a flag about "treat warnings as errors".

**Comment by blueloveTH** [comment]
I'll check all usages of `intptr_t` and `uintptr_t`.
