### ISSUE TITLE
assign a string to a variable : SyntaxError: expected statement end 

### ISSUE THREAD

**Issue by makao007** [blueloveTH/pocketpy#55]
Hi, when I try below code, it throws an error.
`d = r"=function\(\w\)\{[a-z=\.\(\)\"]*;(.*);"`

--------
Error: SyntaxError: expected statement end

**Comment by blueloveTH** [comment]
It seems like `\"` is not escaped correctly.

**Comment by blueloveTH** [comment]
Well, in CPython, `r"\"" == '\\"'`. It does not do escape at all.
I think this behaviour is excepted. One should not use string boundary character in a raw string. It is extremely misleading whether it will be escaped.

For example, if you have `"` in a raw string, you should use `'` or `'''` or `"""` as boundaries.

**Comment by makao007** [comment]
> Well, in CPython, `r"\"" == '\\"'`. It does not do escape at all. I think this behaviour is expected. One should not use string boundary character in a raw string. It is extremely misleading whether it will be escaped or not. So I'd like to notice the user this is an error.
> 
> For example, if you have `"` in a raw string, you should use `'` or `'''` or `"""` as boundaries.

Well, I use it for a regular expression, so I can't use `'` as boundaries.
