### ISSUE TITLE
Sponsorship Inquiry and Technical Advisor Invitation for pikapython

### ISSUE THREAD

**Issue by pikasTech** [blueloveTH/pocketpy#61]
Hello @blueloveTH 

I hope this message finds you well. First and foremost, I want to express my appreciation for the work you've done on the pocketpy project. I believe it's a valuable tool that has been beneficial to many users in the Python community.

I'm writing this issue to let you know that I would like to provide sponsorship to the pocketpy project. While I may not be able to contribute a significant amount, I would still like to offer some support to help the project continue to grow and thrive. 

In addition to this, I would also like to extend an invitation for you to become a technical advisor for the pikapython project (https://github.com/pikastech/pikapython). Your expertise and experience with pocketpy could be extremely valuable for our team as we continue to develop and improve our project. 

Please note that the sponsorship offer stands regardless of whether you accept the technical advisor invitation or not.

Please let me know how I can proceed with the sponsorship and if you're interested in becoming a technical advisor for pikapython. I look forward to hearing from you soon.

Thank you for your time and consideration.

**Comment by blueloveTH** [comment]
Hi @pikasTech .
I am an indie game developer. PocketPy is my hobby project, which is specifically designed for game platforms and aims to provide easy/flexible integration of Python scripting with acceptable performance.

For sponsorship, you can proceed on https://afdian.net/a/dreamer233. Any amount would be appreciated.

I used to browse [pikapython](https://github.com/pikastech/pikapython). It is an amazing project that can run with 4KB RAM and it provides support for a lot of boards. I can see that writing a Python implementation under very strict resource constraints would be very challenging. Your work is extremely valuable in this field.

I am glad to share, but a "Technical Advisor" is too serious for me. I would be interested in joining a technical discussion group for learning and exchanging ideas :)
