### ISSUE TITLE
TODO: impl `pickle` module

### ISSUE THREAD

**Issue by blueloveTH** [blueloveTH/pocketpy#67]
The [pickle](https://docs.python.org/3/library/pickle.html#module-pickle) module implements binary protocols for serializing and de-serializing a Python object structure. “Pickling” is the process whereby a Python object hierarchy is converted into a byte stream, and “unpickling” is the inverse operation, whereby a `bytes` object is converted back into an object hierarchy.

Currently, the `bytes` class in pkpy has been implemented. A serialization mechanism similar to `pickle` is highly needed to achieve deep copying of objects. Our pickle mechanism should have similar functionality to cpython, but it does not necessarily need to be compatible (if achieving compatibility is complex)

**Comment by parthvnp** [comment]
@blueloveTH  Are you looking for contributions to this module? If so, I am eager to work on it.

**Comment by blueloveTH** [comment]
Yes, sure. I need help!
I was looking at cpython's [pickle](https://github.com/python/cpython/blob/3.11/Lib/pickle.py) module, it seems cpython use a special virtual machine for it. However, it is a bit complex.

**Comment by blueloveTH** [comment]
Good luck to you. If you have any questions, just put it here and I will provide help as possible as I can.

**Comment by parthvnp** [comment]
I have started working on the initial implementation for the Pickle module. However, I am currently facing one major issue. Pickling and unpickling heavily rely on `struct` module for packing and unpacking Python objects. This functionally is implemented in [C layer](https://github.com/python/cpython/blob/85c7bf5bcec07beea6064976e6199195cd34329d/Modules/_struct.c#L1642). Currently we don't have any similar functionality to support unpacking and packing of objects directly in the C layer. Should we implement this functionality in the C layer or provide minimal implementations of struct module functions directly in Python?

**Comment by blueloveTH** [comment]
What do you mean packing or unpacking? I'm not familiar with the functionality of struct.

**Comment by parthvnp** [comment]
Perfect. Thank you. I do have a plan in place, I will refine and it share it on discord!

**Comment by blueloveTH** [comment]
I'd like to develop this module myself.
