### ISSUE TITLE
_exec return value

### ISSUE THREAD

**Issue by koltenpearson** [blueloveTH/pocketpy#71]
it seems like _exec should give you the pyobject that results from the last statement it runs, but instead it seems like it always returns None.

This might be intended behavior and if it is that is fine, I just figured I would check

**Comment by blueloveTH** [comment]
This is not controlled by `_exec`.
In `EXEC_MODE`, the last bytecode clean the stack and returns None
In `EVAL_MODE`, the last bytecode returns the last expression

**Comment by koltenpearson** [comment]
Gotcha, makes sense. Not an issue then. Thanks!
