### ISSUE TITLE
TODO: impl `datetime` module

### ISSUE THREAD

**Issue by blueloveTH** [blueloveTH/pocketpy#78]
We want to provide a minimum set of `datetime`.
See https://pocketpy.dev/modules/datetime/ for the api set.

**Comment by FinBird** [comment]
Can I help? Acorrding to your api set, Iimplement the`timedelta`class. in [Link](https://github.com/FinBird/pocketpy/blob/main/python/datatime.py)

**Comment by blueloveTH** [comment]
Hi! Thanks for your trying.
Directly copy things from cpython's stdlib is not a good idea because they use a lot of syntax pkpy does not support. (someone tried before)

Some syntax like `a < b < c` behave different between cpython and pkpy.
`a = b = 1` is also unavailable. String format methods also have limitations.

**Comment by FinBird** [comment]
Get it, I will check it carefully in pkpy.
Besides, I found that some function such as `divmod` and `modf` is not avaliable in pkpy's `math`lib, will you add it? Implementing it in pure Python may not a good idea.
Thank you.

**Comment by blueloveTH** [comment]
`divmod` is implemented. For others you can do it in pure python, if it is critical we can move them to cpp later.

**Comment by FinBird** [comment]
完善了`timedelta`类之后，发现已经有人已经pull了https://github.com/blueloveTH/pocketpy/pull/77
那我暂时不继续做下去了。需要的话，我可以帮忙完善那个pull的`datetime` api。

**Comment by blueloveTH** [comment]
#77 does not work. So I opened this issue.

**Comment by FinBird** [comment]
Ok, I fix the `timedelta` class. https://github.com/FinBird/pocketpy/blob/main/python/datetime.py

**Comment by FinBird** [comment]
Suggestion:
Something should be implement in cpp?
Exception:`TypeError`,`NotImplemented`,`OverflowError`
Function:[`math.modf`](https://docs.python.org/3/library/math.html#math.modf)，[`time.localtime`](https://docs.python.org/3/library/time.html#time.localtime)

**Comment by blueloveTH** [comment]
Exceptions are dummy. No need to define exception class. Just raise <name>.

**Comment by blueloveTH** [comment]
`math.modf` and `time.localtime` was added. `time.localtime` returns a `dict`.
