### ISSUE TITLE
About the operation of large numbers

### ISSUE THREAD

**Issue by gzzyyxh** [blueloveTH/pocketpy#8]
When I used this interpreter to calculate `99**99`, there was an overflow. Do you need to solve this problem? I know this is a lightweight interpreter, and I'm not a game developer, just a simple curiosity, thanks.

**Comment by blueloveTH** [comment]
`int` in PkPy is 64 bit. There is no plan to support big integers.
Because they are usually used in numerical analysis, but rarely in game development.
