### ISSUE TITLE
Add partial execution of compiled code

### ISSUE THREAD

**Issue by SuperSpaceEye** [blueloveTH/pocketpy#88]
Idk how hard it would be to implement, but here is my idea:
Instead of executing whole code at once add a function that will work something like this:
```c++
auto code = vm->compile("some long python code", EXEC_MODE)
auto max_pass_bytecode_instructions = 1000 // maximum amount of instructions that vm can execute in one pass
while (true) {
   //nullptr because code is not finished executing
    if (vm->_exec_partial(max_pass_bytecode_instructions, code, vm->_main) != nullptr) {break;}
}
```
This will allow to have several separate VM's running on one thread without making several threads for each VM.

**Comment by blueloveTH** [comment]
Could you show a actual use case of having such fine-grained control?
In fact, you can split code by lines and execute them line by line. That is much easier to understand than split by bytecode.

**Comment by SuperSpaceEye** [comment]
I want to make a minecraft mod like computer craft, except it will run python with the help of your vm (Through JNI it will call some wrapper functions, though I still think on how to properly code it), so I don't really want to make users code in a specific way, nor do I want to make a thread for (potentially) hundreds of computers.

**Comment by blueloveTH** [comment]
An idea is to write a `yield`-based coroutine. Each computer runs in a coroutine.
