### ISSUE TITLE
post 1.0 bind_builtin_func not allowing lambda variable capture

### ISSUE THREAD

**Issue by shakfu** [blueloveTH/pocketpy#89]
I've been recently converting [my project's pocketpy code](https://github.com/shakfu/py-js/tree/main/source/projects/pktpy) to the latest pocketpy 1.0 version and I found (at least for me) what looks like a bug or a feature regression:

In the older 0.9.5 code, I could a bind a builtin function like this without issues:

```c++
    x->py->vm->bind_builtin_func<1>("out_int", [x](VM* vm, Args& args) {
        i64 a = CAST(i64, args[0]);
        outlet_int(x->outlet, a);
        return vm->None;
    });
```

When I translated the same code to the new 1.0+ idioms:

```c++
    x->py->vm->bind_builtin_func<1>("out_int", [x](VM* vm, ArgsView args) {
        i64 a = CAST(i64, args[0]);
        outlet_int(x->outlet, a);
        return vm->None;
    });
```
I cannot compile it and I get the following error:

```text
src/pktpy/pktpy.cpp:436:16: fatal error: no matching member function for call to 'bind_builtin_func'
    x->py->vm->bind_builtin_func<1>("out_int", [x](VM* vm, ArgsView args) {
    ~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~
src/pktpy/pocketpy.h:3727:15: note: candidate function template not viable: 
no known conversion from '(lambda at src/pktpy/pktpy.cpp:436:48)' to 'pkpy::NativeFuncC' (aka 'pkpy::PyObject *(*)(pkpy::VM *, pkpy::ArgsView)') for 2nd argument
    PyObject* bind_builtin_func(Str name, NativeFuncC fn) {
              ^
```

Is there any way to resolve this?

**Comment by blueloveTH** [comment]
Yes, this is a feature regression. Functions to be bind must be a C function pointer (no capture).
The reason is, captured bindings lead to severe "code-bloat" and performance degradation.

**Comment by blueloveTH** [comment]
This makes users to use capture with caution. In most cases, there is a way to not to use capture.
If one think there is no way, we also provide an explicit capture.

```cpp
PyObject* obj = vm->bind_builtin_func<1>("out_int", [](VM* vm, ArgsView args) {
        // use `lambda_get_userdata<T>` to access the captured data
        int x = lambda_get_userdata<int>(args.begin());
        return VAR(x);
});
// explicit capture some data
CAST(NativeFunc&, obj).set_userdata(10);
```

**Comment by shakfu** [comment]
Thanks for your help.

In my case `x` isn't just some variable which will be returned, it's a pointer to the main struct of the application which has as a member an instance of a class which has its member an instance of the pocketpy `VM*`, hence `x->py->vm->bind_builtin_func`. I need to give the lambda function access to this pointer so I can selectively expose parts of the applications functions and behavior to python code. 

In any case, your solution seems to compile without errors (I haven't tested it yet):

```c++
x->py->vm->bind_builtin_func<1>("out_int", [](VM* vm, ArgsView args) {
        t_pktpy *x = lambda_get_userdata<t_pktpy *>(args.begin());
        i64 a = CAST(i64, args[0]);
        outlet_int(x->outlet, a);
        return vm->None;
    });
```

Frankly, I found the older way more intuitive and "standard", but I won't argue if the new way is more performant.

**Comment by shakfu** [comment]
I've tested your solution and it works so I'm going to close this issue. Thanks!

**Comment by blueloveTH** [comment]
I think we can make a config macro to enable std::function that allows capture. If one cares convenience more than performance.

**Comment by shakfu** [comment]
> I think we can make a config macro to enable std::function that allows capture. If one cares convenience more than performance.

Yes, please, I'm still having trouble with the current system in a strange case:

In version 0.9.5 this worked:

```c++
    x->py->vm->bind_builtin_func<0>("location", [x](VM* vm, Args& args) {
        t_symbol* sym = pktpy_get_path_to_external(x);
        outlet_anything(x->outlet, sym, 0, (t_atom*)NIL);
        return vm->None;
    });
```

but this converting it to 1.0+ idiom causes an inexplicable crash:

```c++
    x->py->vm->bind_builtin_func<0>("location", [](VM* vm, ArgsView args) {
        t_pktpy *x = lambda_get_userdata<t_pktpy *>(args.begin());
        t_symbol* sym = pktpy_get_path_to_external(x);
        outlet_anything(x->outlet, sym, 0, (t_atom*)NIL);
        return vm->None;
    });
```

**Comment by blueloveTH** [comment]
Could you please provide more infomation about this crash?

**Comment by shakfu** [comment]
> Could you please provide more infomation about this crash? If x is a pointer, the two idioms are the same.
Or maybe we have a bug on this.

`x` is a pointer to a struct. The cash occurs in the latter case with the second use of `x` in this line which worked fine in version 0.9.5:

```
outlet_anything(x->outlet, sym, 0, (t_atom*)NIL);
```

If I remove this line, there is no crash. If I substitute another function in its place which  uses `x` then a crash occurs again. So it strangely seems due to the second use of `x` while the first use works as expected. 

Like I said all very strange and unintuitive.

**Comment by blueloveTH** [comment]
Have you used `CAST(NativeFunc&, obj).set_userdata(...);` to set `x`? If not, `lambda_get_userdata` will return some junk data.

**Comment by shakfu** [comment]
Thanks for your question. It looks that was the problem. I didn't use `.set_userdata(x)` to set `x`.

This worked for me as per your solution:

```c++
    PyObject* obj = x->py->vm->bind_builtin_func<0>("location", [](VM* vm, ArgsView args) {
        t_pktpy *x = lambda_get_userdata<t_pktpy *>(args.begin());
        t_symbol* sym = pktpy_get_path_to_external(x);
        outlet_anything(x->outlet, sym, 0, (t_atom*)NIL);
        return vm->None;
    });
    py_cast<NativeFunc&>(x->py->vm, obj).set_userdata(x);
```

**Comment by blueloveTH** [comment]
You can create a `user_config.h` in the same directory as `pocketpy.h` to override some default settings.

1. Copy [src/config.h](https://github.com/blueloveTH/pocketpy/blob/main/src/config.h) and rename it to `user_config.h`.
2. Define a macro `PK_USER_CONFIG` in `user_config.h`. This invalidates the default `config.h` and enables your `user_config.h`.
3. Edit `user_config.h` to override default settings.

By setting `PK_ENABLE_STD_FUNCTION` to 1 you will get the old ways.

**Comment by blueloveTH** [comment]
In linux platform, with/without `PK_ENABLE_STD_FUNCTION` binary size is `1.6 MB`/`1.1 MB`.

**Comment by shakfu** [comment]
Wow, thanks very much, I will try it out!

**Comment by shakfu** [comment]
@blueloveTH here's my feedback after testing `PK_ENABLE_STD_FUNCTION` via `user_config.h`

With `PK_ENABLE_STD_FUNCTION 0`, compilation time is fast and my pocketpy-based plugin size is around 0.98M

With `PK_ENABLE_STD_FUNCTION 1`, compilation time is very slow and my plugin size is now around 1.5M

Given all the fixes which made my code work with the new way, and the above compilation and size advantages, I won't be going back to the old-style and for me going forward `PK_ENABLE_STD_FUNCTION` will remain at `0`!

But, in any case, appreciate your help and `user_config.h` is nice to have. 👍
