### ISSUE TITLE
Is there an an equivalent of NativeProxyFunc in 1.0+

### ISSUE THREAD

**Issue by shakfu** [blueloveTH/pocketpy#90]
Just asking if there's an equivalent of NativeProxyFunc in 1.0+. If not, no worries.

**Comment by blueloveTH** [comment]
According to the zen of python,
> There should be one-- and preferably only one --obvious way to do it.

Meta template things were removed from this project. The only way to do bindings is to use raw bindings.

**Comment by blueloveTH** [comment]
You can still write some meta template wrapper.
These wrappers are considered **not a part of this library**. Think about cpython and pybind11.

This makes our api more compact.
