### ISSUE TITLE
Got a compile error when I included the pocketpy.h in my project

### ISSUE THREAD

**Issue by roverzhong** [blueloveTH/pocketpy#94]
I just downloaded the latest version of v1.0.3 of pocketpy.h and added it into my existing project.

When I try to compile my test.cpp in the VS 2017, I got a compile error and please see below screenshot:

![image](https://github.com/blueloveTH/pocketpy/assets/3203931/3d7a1a56-180f-4360-ab01-23d8bb1fa64c)

However, when I created a completely new project and do the same test, the compile error was gone.

**Comment by blueloveTH** [comment]
That's pretty strange! I haven't tested it in vs2017 because this library depends on `--std=c++17`.
This compile error may relate to a compiler support issue.

**Comment by blueloveTH** [comment]
Another possibility is name redefinition. See if your project defines some global variable or macro named `Type` or `type`.

**Comment by roverzhong** [comment]
> Another possibility is name redefinition. See if your project defines some global variable or macro named `Type` or `type`.

Thanks for the quick feedback! Yes, I have double checked that I'm using the --std=C++17 for each C++ project.

Yes, there are some macro or enum defined as 'Type' however they are organized well by the namespace. The original projects don't have the compile error.

The problem seems only happen in below two methods in the definition of 'ManagedHeap'

```
template<typename T>
    PyObject* gcnew(Type type, T&& val){
        using __T = Py_<std::decay_t<T>>;
        PyObject* obj = new(pool64.alloc<__T>()) __T(type, std::forward<T>(val));
        gen.push_back(obj);
        gc_counter++;
        return obj;
    }

    template<typename T>
    PyObject* _new(Type type, T&& val){
        using __T = Py_<std::decay_t<T>>;
        PyObject* obj = new(pool64.alloc<__T>()) __T(type, std::forward<T>(val));
        obj->gc.enabled = false;
        _no_gc.push_back(obj);
        return obj;
    }
```

For others, the 'Type' could be linked correctly.

Besides, when I looked into the source of pocketpy.h, I'm curious why there are multiple blocks using the same 'pkpy'.

Looking forwards to your suggestion!

**Comment by blueloveTH** [comment]
Our `Type` is also wrapped in `pkpy` namespace. However, if `Type` in your project is a macro, it does not work. Because macro is a global thing which cannot be wrapped in a namespace.

**Comment by roverzhong** [comment]
> Our `Type` is a struct, also wrapped in `pkpy` namespace. However, if `Type` in your project is a macro, it does not work. Because macro is a global thing which cannot be wrapped in a namespace.
> 
> I think there are nothing to do with pocketpy. You may need to edit your original macro to use a less common name.

My fault on my previous comment, we don't have a macro defined as 'Type', but we do have one struct defined as Type but in different namespace. In addition, we defined several enum "Type" in some class.

**Comment by roverzhong** [comment]
@blueloveTH I still have a question on the 'Type' issue, I just made a simple test project which only includes one pocketpy.h file and write some simple test code. The project could be compiled successfully without any error. However, when I open the head file in Visual Studio 2022 and had a look at the 'Type' (at the same code line) and tried to find its related symbols by pressing 'F12', please see below screenshot, it still confused me why it couldn't locate the correct wrapped namespace, instead there are lots of 'Type' referenced in the Windows head files.  

![image](https://github.com/blueloveTH/pocketpy/assets/3203931/39682e4e-e1cb-4034-94f4-a086637d5e65)

I don't have the knowledge of Cython, so it's not a easy thing for me to figure out the root cause, can you help have a look at this issue?

**Comment by blueloveTH** [comment]
You can upload a MRE (minimum reproducible example) so I can test it on my machine.

**Comment by blueloveTH** [comment]
> Besides, here attached the simple test project mentioned in my last comment, just curious why the Visual Studio intelliSence could not work well with the specific 'Type' in the 'ManagedHeap' methods.

This may be a msvc's intellisense issue. The false alarm does not affect the compiling process.

**Comment by blueloveTH** [comment]
I think msvc does not give you the correct error position and information. There is some other issues in your project.

**Comment by roverzhong** [comment]
I found a way to fix this compile problem with my 'large project'. I apologize for the mis-leading (my previous analysis) on the 'pkpy::Type', in fact the compiler is reporting at the syntax error at the 'type'. 

I don't know the root cause and now it could be compiled successfully with below changes in the .h file:

![image](https://github.com/blueloveTH/pocketpy/assets/3203931/12c7351e-239e-44b8-85aa-7bcad2f6a06f)

I will close this issue.

Thanks again for all the help! @blueloveTH Really brilliant work!

**Comment by blueloveTH** [comment]
Thanks..for your reporting.

**Comment by blueloveTH** [comment]
Try to suppress this by your solution on windows. See [here]9https://github.com/blueloveTH/pocketpy/commit/3148dab556f1f3534e2595db3234d2c4fede37e4).

```cpp
#if _WIN32
        // https://github.com/blueloveTH/pocketpy/issues/94#issuecomment-1594784476
        PyObject* obj = new(pool64.alloc<__T>()) Py_<std::decay_t<T>>(type, std::forward<T>(val));
#else
        PyObject* obj = new(pool64.alloc<__T>()) __T(type, std::forward<T>(val));
#endif
```
