### ISSUE TITLE
Another lambda capture issue with PrintFunc 

### ISSUE THREAD

**Issue by shakfu** [blueloveTH/pocketpy#95]
I want to give some background on a small issue in my code. I have wrapped some pocketpy functionality in a class `PktpyInterpreter`, and in this class I have a method `eval_text` which should silently try to `eval` some pocketpy code (i.e. without `stderr` output if it fails) and then try to `exec` it and output error to stderr if that fails.

The way I wanted to make this work is to have a private `disable_stderr` instance variable of the class and have it checked in the `_stderr` function.

Because  the signature of `_stderr` is `PrintFunc` instead of `std::function`, no captures are allowed in this case and `this->disable_stderr` var is not accessible inside `this->_stderr`.

Is there any way around this to reach the same objective: i.e. selectively disable `stderr` output for one particular case?

```c++
PktpyInterpreter::PktpyInterpreter()
{
    this->name = symbol_unique();
    this->pythonpath = gensym("");
    this->source_name = gensym("");
    this->source_path = gensym("");
    this->path_code = 0;
    this->loglevel = log_level::PY_LOG_LEVEL;
    this->disable_stderr = false;
    this->vm = new VM(false); // vm->enable_os = false

    this->vm->_stdout = [](VM* vm, const Str& s) {
        const char* stdout_output = s.c_str_dup();
        post((char*)stdout_output);           
    };

    this->vm->_stderr = [&](VM* vm, const Str& s) {
        if (!this->disable_stderr) {
            const char* stderr_output = s.c_str_dup();
            error((char*)stderr_output);
        }
    };
}

// ...


PyObject* PktpyInterpreter::eval_text(char* text)
{
    this->disable_stderr = true;
    PyObject* result = this->vm->exec(text, "<eval>", EVAL_MODE);
    this->disable_stderr = false;
 
    if (result == NULL) {
        if (this->vm->exec(text, "main.py", EXEC_MODE) != NULL) {
            return this->vm->None;
        }
    } else {
        return result;
    }
    return NULL;
}

```

**Comment by shakfu** [comment]
I have managed to get this to work by converting `PrintFunc` from a function pointer to a `std::function` as follows in line 3435-3436 of `pocketpy.h`

```c++
//typedef void(*PrintFunc)(VM*, const Str&);
typedef std::function<void(VM*, const Str&)> PrintFunc;
```

This has (at least for me) no impact on time or size of binary.

May I suggest this is enabled/disabled via a `#define PK_ENABLE_STD_FUNCTION_PRINTFUNC 1` or similar as follows? :

```c++
#ifdef PK_ENABLE_STD_FUNCTION_PRINTFUNC
typedef std::function<void(VM*, const Str&)> PrintFunc;
#else
typedef void(*PrintFunc)(VM*, const Str&);
#endif
```

**Comment by blueloveTH** [comment]
Well, I think you can subclass `VM` to implement `PktpyInterpreter`. So you can do `static_cast<PktpyInterpreter*>(vm)` to get all additional fields, instead of using `std::function`.

**Comment by shakfu** [comment]
> Well, I think you can subclass VM to implement PktpyInterpreter. So you can do static_cast<PktpyInterpreter*>(vm) to get all additional fields, instead of using std::function for each possible C-style callbacks.

> This is different from bindings. You are extending the VM (not do some patches). So subclassing is a better design pattern.

Thanks, you are right, although I tend to avoid inheritance, in this case, It makes sense... and seems to work to fine:

```c++
// main.cpp
#include "pocketpy.h"
#include "stdio.h"

using namespace pkpy;

class PktpyInterpreter : public VM { };

int main() {
    PktpyInterpreter *py = new PktpyInterpreter();
    PyObject* result = py->exec("1+1", "<eval>", EVAL_MODE);
    if (is_int(result)) {
        int int_result = py_cast<int>(py, result);
        printf("result: %d\n", int_result);
    }
}
```
and
```bash
$ g++ --std=c++17  -O2 -Wall -Wfatal-errors -Wno-sign-compare -Wno-unused-variable -fno-rtti \
       -stdlib=libc++ -o main main.cpp
$ ./main
result: 2
```

**Comment by shakfu** [comment]
Thanks for your help. It was a quick and successful conversion and I ended up as per your advice with the following member function in `PktpyInterpreter`:

```c++
    this->_stderr = [](VM* vm, const Str& s) {
        if (!static_cast<PktpyInterpreter*>(vm)->disable_stderr) {
            const char* stderr_output = s.c_str_dup();
            error((char*)stderr_output);
        }
    };
```
