### ISSUE TITLE
Wrapping of classes and structs

### ISSUE THREAD

**Issue by shakfu** [blueloveTH/pocketpy#96]
Although there is no documented example of a class being wrapped (only structs are used for some reason), I found that it's possible to do the same to classes. 

For example, the class below works fine. 

Is there any reason for the overt preference for structs in the documentation? 

```c++

class PyPoint {
private:
    float x;
    float y;

public:
    PY_CLASS(PyPoint, test, PyPoint)

    PyPoint(float x, float y) : x(x), y(y) {}

    static void _register(VM* vm, PyObject* mod, PyObject* type){
        vm->bind_constructor<3>(type, [](VM* vm, ArgsView args){
            float x = CAST_F(args[1]);
            float y = CAST_F(args[2]);
            return VAR_T(PyPoint, x, y);
        });
        vm->bind_method<0>(type, "__repr__", [](VM* vm, ArgsView args){
            PyPoint& self = CAST(PyPoint&, args[0]);
            std::stringstream ss;
            ss << "PyPoint(" << self.x << ", " << self.y << ")";
            return VAR(ss.str());
        });
    }
};
```

**Comment by blueloveTH** [comment]
In c++, `class` and `struct` are the same except for the default visibility settings.

**Comment by shakfu** [comment]
> In c++, class and struct are the same except for the default visibility settings.

Thanks, yes I was aware of that, but was just curious why there were no examples of classes being wrapped.
